### ISSUE TITLE
figure out details of sensor tracking on journal website

### ISSUE THREAD

**Issue by egonw** [jcheminform/jcheminform#8]
I just got alerted that without asking our journal website tries to access movement/light sensors. That sounds a bit weird:

 - [ ] why does the website track these sensors?
 - [ ] if the reason is detecting bot access, why does BMC (or SpringerNature) think that is needed? 
 - [ ] can it be turned off alltogether? because we want bots to access the website
